[package]
name = "json2atom"
version = "0.2.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
time = { version = "0.3", features = ["std", "formatting", "parsing", "local-offset"] }
